training_pipeline_config : 
  pipeline_name : rentals
  artifact_dir : artifactt

data_ingestion_config :
  dataset_download_url : https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip
  raw_data_dir : raw_data
  zip_download_dir : zip_data
  ingested_dir : ingested_data
  ingested_train_dir : ingested_train_data
  ingested_test_dir : ingested_test_data

